name: Self Heal
on: push
jobs:
  heal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean Install
        run: npm install --package-lock-only || npm audit fix --force
